### ISSUE TITLE
Feature: User can search for movies 

### ISSUE THREAD

**Issue by Dprosser4** [Dprosser4/WatchIT#1]
## ⚙️ Feature

User can search for movies

## 📐 Functionality

A user will first see the get started graphic if they have not visited before, then after get started is click it will land on the movie search form. User can type any movie in and a list of hits will populate on the results view. 

## 🖼️ Wireframes

<img width="1154" alt="Screen Shot 2023-01-09 at 11 42 11 AM" src="https://user-images.githubusercontent.com/98434681/211394493-38e61d35-774b-45ab-9990-fc954a3b4041.png">
<img width="1156" alt="Screen Shot 2023-01-09 at 11 50 03 AM" src="https://user-images.githubusercontent.com/98434681/211395305-079828ac-759f-41ee-aaed-c6f9d2dbf756.png">

## ✅ Task List
- [x] Create the HTML for the 3 views
   - [x] the search movies form view
   - [x] the results of search view
   - [x] the get started initial view
- [x] Style the CSS to match figma layouts
   - [x] write css for mobile first
   - [x] adjust the styling to adapt fluidly to desktop
- [x] add an event listener on the get start button
   - [x] on click hide the initial view and change to the search view
- [x] add an event listener to the search form button with type submit
   - [x] pass the string from the search input to get request for search results data 
   - [x] change view to results view
- [x] make a render dom function that takes the data from the search adds photo and titles to the results view
   - [x] check if any results were found if not show no results found 
- [x] add an event listener to the search icon in the  nav bar that switches the view back to the search form 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
