### ISSUE TITLE
Feature: User can  see details of movie (short plot summary, year, genre ect.)

### ISSUE THREAD

**Issue by Dprosser4** [Dprosser4/WatchIT#2]
## ⚙️ Feature
user will see a see details of movie
## 📐 Functionality

user will see a see details button on each result on the results page. when clicked it shows a details page that has the title. director, year and short plot summary 

## 🖼️ Wireframes
<img width="545" alt="Screen Shot 2023-01-11 at 10 46 40 AM" src="https://user-images.githubusercontent.com/98434681/211892131-d164eb5a-8db9-4e40-be21-729bb88d3fcd.png">
<img width="1121" alt="Screen Shot 2023-01-11 at 10 46 59 AM" src="https://user-images.githubusercontent.com/98434681/211892155-8c99d008-0f35-4b6f-a296-42d1fa40e19f.png">

## ✅ Task List

- [x] add back dummy data html and style the new see details button 
- [x] write html and css for new details view with dummy data
   - [x] on mobile there will be a image in a full column and movie details under in a full column with a back button
   - [x] on desktop it will change to side by side column halfs (col-6)  
- [x] adjust the dom render function on for the results view to add the details button
   - [x] each detail button should also have an attribute with the movies unique ID from the api so it can be passed into a new http request
- [x] add an event listener to the container of all the results that delegates to the details button that was clicked 
   - [x] add details view to the view swap function that is called when the button is clicked
- [x] add an event listener to the back button in details view
   - [x] when clicked the button should swap back to the results view with results still there   
- [x] pass the unique movie ID attribute into a new http request to get that movies data
- [x] use the movies data to create the dom elements for the details view
   - [x]  if the user navigates back to the results page clear the details views dom tree 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
