### ISSUE TITLE
Feature: User can add movie to watch list

### ISSUE THREAD

**Issue by Dprosser4** [Dprosser4/WatchIT#3]
## ⚙️ Feature
User can add movie to watch list
## 📐 Functionality
the user can see an add to watchlist button on the results view and and details view. when clicked it adds that movie to the watch list. there is now a watch list view accessible from the nav bar that shows all the movies in the watch list.
## 🖼️ Wireframes
![Screen Shot 2023-01-12 at 09 32 45 AM](https://user-images.githubusercontent.com/98434681/212138291-8109fcc0-ab08-467e-a2c2-8b8630b6ae80.png)
![Screen Shot 2023-01-12 at 09 33 29 AM](https://user-images.githubusercontent.com/98434681/212138424-c4cca7f4-473c-4c39-b2f3-08939132f2d8.png)
## ✅ Task List

- [x] add back dummy data and write html and css to match figma
   - [x] add the watch list button to results view
   - [x] add the watch list button to details view
   - [x] add watchlist to nav bar
   - [x] create a new watch list view
   - [x] add dummy data to style
- [x] update results render function to add the new watch button 
- [x] update details render function to add the new button 
- [x] update view swap function to work with watchlist navigation
- [x] add an event listener for the watch list buttons 
- [x] write a new function for when the buttons are clicked that adds the movies data to the users watch list array
- [x] write a new function that loops through the watchlist array and creates a dom tree for the watchlist
   - [x] if the array is empty add a no movies add yet item
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
