### ISSUE TITLE
Feature: User can  delete movies from watch list 

### ISSUE THREAD

**Issue by Dprosser4** [Dprosser4/WatchIT#4]
## ⚙️ Feature
User can delete movies from watch list
## 📐 Functionality
in the watch list view a user sees a delete button. when clicked it give a are you sure modal and if confirmed it removes the movie from watch list
## 🖼️ Wireframes
![Screen Shot 2023-01-13 at 1 42 11 PM](https://user-images.githubusercontent.com/98434681/212424530-874abdf0-e38b-4d4e-bd4e-db26a1ba8651.png)

![Screen Shot 2023-01-13 at 1 42 30 PM](https://user-images.githubusercontent.com/98434681/212424585-3e28d831-b4c8-4484-b099-02be680c759c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] write html and css for modal and new delete button
- [x] adjust watchlist render function to add delete button 
- [x] adjust view swap to hide and show modal
- [x] add event listener to modal buttons 
- [x] write new function that removes the deleted item from the array in data 
- [x] make sure the watch list re renders when the item is deleted
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
