### ISSUE TITLE
Feature: User can  user can mark movie as watched

### ISSUE THREAD

**Issue by Dprosser4** [Dprosser4/WatchIT#5]
## ⚙️ Feature

User can user can mark movie as watched
## 📐 Functionality
user will see a watched? button and if clicked it will be changed to greyed out watched to keep track of the movies they have seen.
## 🖼️ Wireframes

![Screen Shot 2023-01-15 at 14 18 19 PM](https://user-images.githubusercontent.com/98434681/212570138-8024c084-c31c-4df1-bd5a-97603166ee8d.png)
![Screen Shot 2023-01-15 at 14 18 32 PM](https://user-images.githubusercontent.com/98434681/212570140-a0cb0510-7f85-47d9-a9fe-20d17c769904.png)

## ✅ Task List
- [x] add watched button to the watchlist dom create function
- [x] use the event delegation on the watchlist to target watch? button
- [x] add a new data property on movies array that keeps track of whether a movie is watched or not
- [x] when clicked
   - [x] grey the button out and change text to Watched
   - [x] move that movies data to the end of the array 
   - [x] update the movies array to watched 
   - [x] re render the dom in the correct order with buttons correct
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
